import type { SyncProviderClient } from '../syncTypes'
import {
  convexConfigured,
  deleteSharedBlob,
  deleteRemoteVault,
  deleteRemoteBlob,
  getConvexAuthToken,
  getCloudAuthStatus,
  getSharedBlob,
  getRemoteBlob,
  getEntitlementStatus,
  listAdminMembers,
  listOrgMemberDevices,
  listOrgMemberships,
  listSharedVaultsByOrg,
  listRemoteVaultsByOwner,
  openSharedVault,
  pullRemoteSnapshot,
  pullRemoteVaultByOwner,
  pullSharedVaultSnapshot,
  putRemoteBlob,
  putSharedBlob,
  pushRemoteSnapshot,
  pushSharedVaultSnapshot,
  finalizeSharedVaultMemberAccess,
  refreshSharedVaultAccess,
  registerOrgDeviceKey,
  shareVaultWithOrg,
  setConvexAuthContext,
  setConvexAuthToken,
  unshareVaultFromOrg,
} from '../convexApi'

export const convexProvider: SyncProviderClient = {
  configured: convexConfigured,
  setAuthToken: setConvexAuthToken,
  getAuthToken: getConvexAuthToken,
  setAuthContext: setConvexAuthContext,
  pullRemoteVaultByOwner,
  listRemoteVaultsByOwner,
  pullRemoteSnapshot,
  pushRemoteSnapshot,
  deleteRemoteVault,
  putRemoteBlob,
  getRemoteBlob,
  deleteRemoteBlob,
  getCloudAuthStatus,
  listOrgMemberships,
  listSharedVaultsByOrg,
  listAdminMembers,
  listOrgMemberDevices,
  registerOrgDeviceKey,
  shareVaultWithOrg,
  refreshSharedVaultAccess,
  unshareVaultFromOrg,
  openSharedVault,
  finalizeSharedVaultMemberAccess,
  pullSharedVaultSnapshot,
  pushSharedVaultSnapshot,
  putSharedBlob,
  getSharedBlob,
  deleteSharedBlob,
  fetchEntitlementToken: getEntitlementStatus,
  subscribeToVaultUpdates: () => () => {},
}
